export default {
  Name: 'vtexcommerce-abandoned-cart',
  FriendlyName: 'Abandoned Cart',
  Description: 'Notify to the user that he had an order pending to finish',
  IsDefaultTemplate: false,
  AccountId: null,
  AccountName: '{(accountName}}',
  ApplicationId: null,
  IsPersisted: true,
  IsRemoved: false,
  Type: '',
  Templates: {
    email: {
      To: '{{email}}',
      CC: null,
      BCC: null,
      Subject: 'Lost Cart!',
      Message:'Template Example',
      Type: 'E',
      ProviderId: '00000000-0000-0000-0000-000000000000',
      ProviderName: null,
      IsActive: true,
      withError: false,
    },
    sms: {
      Type: 'S',
      ProviderId: null,
      ProviderName: null,
      IsActive: false,
      withError: false,
      Parameters: [],
    },
  },
}
